config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:edit, :update]
  root 'users#new'
  post "/check_unique_user" => "users#check_unique_user", :as => :check_unique_user
  post "/check_unique_email" => "users#check_unique_email", :as => :check_unique_email
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :nickname, presence: true, uniqueness: { case_sensetive: false }
  validates_format_of :nickname, :with =>  /[a-z]([a-z][0-9])*/i
  validates :firstname, presence: true
  validates_format_of :firstname, :with => /\A[а-яё]+\z/i
  validates :lastname, presence: true
  validates_format_of :lastname, :with => /\A[а-яё]+\z/i
  validates :email, presence: true, uniqueness: { case_sensetive: false }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :password, presence: true
  validates :password, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy], except: [:check_unique_user, :check_unique_email]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def check_unique_user
    @user = User.find_by nickname: params[:nickname]
    @result = if @user.nil? then 'uniq' else 'notuniq' end
    respond_to do |format|
      format.js { render :file => "users/check_unique_user.js.erb" }
    end
  end

  def check_unique_email
    @user = User.find_by email: params[:email]
    @result = if @user.nil? then 'uniq' else 'notuniq' end
    respond_to do |format|
      format.js { render :file => "users/check_unique_email.js.erb" }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  #def edit
  #end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Регистрация завершена.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
=begin
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
=end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nickname, :firstname, :lastname, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Regform</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div id="container">
  <%= form_for(user) do |f| %>
    <table>
      <tr>
        <td class="label">Никнейм:</td>
        <td class="icon nickname-icon"></td>
        <td class="text-bold"><%= f.text_field :nickname, size: 25 %></td>
        <td class="errors nickname-error"></td>
      </tr>
      <tr>
        <td class="label">Имя:</td>
        <td class="icon firstname-icon"></td>
        <td class="text-bold"><%= f.text_field :firstname, size: 25 %></td>
        <td class="errors firstname-error"></td>
      </tr>
      <tr>
        <td class="label">Фамилия:</td>
        <td class="icon lastname-icon"></td>
        <td class="text-bold"><%= f.text_field :lastname, size: 25 %></td>
        <td class="errors lastname-error"></td>
      </tr>
      <tr>
        <td class="label">Электронная почта:</td>
        <td class="icon email-icon"></td>
        <td class="text-bold"><%= f.email_field :email %></td>
        <td class="errors email-error"></td>
      </tr>
      <tr>
        <td class="label">Пароль:</td>
        <td class="icon password-icon"></td>
        <td class="text-bold"><%= f.password_field :password %></td>
        <td class="errors password-error"></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td><%= f.submit 'Готово', disabled: true, class: 'submit-button' %></td>
        <td></td>
        <td></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/users/check_unique_email.js.erb
<% if @result == 'uniq'%>
  $('td.email-error').text('');
  $('td.email-icon').html('<img src="/assets/galka.jpg">');
  unblockButton();
<% else %>
  $('td.email-error').text('Такой email уже занят');
  $('input.submit-button').attr('disabled', true);
  $('td.email-icon').html('<img src="/assets/red-icon.jpg">');
<% end %>

app/views/users/check_unique_user.js.erb
<% if @result == 'uniq'%>
  $('td.nickname-error').text('');
  $('td.nickname-icon').html('<img src="/assets/galka.jpg">');
  unblockButton();
<% else %>
  $('td.nickname-error').text('Такой никнейм уже занят');
  $('input.submit-button').attr('disabled', true);
  $('td.nickname-icon').html('<img src="/assets/red-icon.jpg">');
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Пользователи</h1>

<table>
  <thead>
    <tr>
      <th>Никнейм</th>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Показать', user %></td>
        <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы учерены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Регистрация', new_user_path %>

app/views/users/new.html.erb
<h2 class="registration-header">Регистрация:</h2>

<%= render 'form', user: @user %>

<%= link_to 'Список пользователей', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Никнейм:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Имя:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Фамилия:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Список пользователей', users_path %>